use crate::{addr_var, utils::address::addr};

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub enum GameState {
    None = -1,
    MainMenu = 0x0,
    Gameplay = 0x1,
    Load = 0x2,
    Boot = 0x3,
    MultiInit = 0x4,
    MultiShutdown = 0x5,
    ConnectingToInvite = 0x6,
    MainMenuOptions = 0x7,
    MainMenuOptionsDisplay = 0x8,
    MainMenuOptionsAudio = 0x9,
    MainMenuOptionsLive = 0xa,
    MainMenuOptionsLiveQuickmatch = 0xb,
    MainMenuOptionsGameOptions = 0xc,
    MainMenuOptionsExtras = 0xd,
    Cheats = 0xe,
    IngameOptions = 0xf,
    PlayerDeathOptions = 0x10,
    SonyOptions = 0x11,
    ControllerOptions = 0x12,
    WreckingCrewMainMenu = 0x13,
    WreckingCrewCharacterSelect = 0x14,
    WreckingCrewScoreboard = 0x15,
    MultiplayerLive = 0x16,
    MultiplayerChangeMatchmaking = 0x17,
    MultiplayerSearchMatchmaking = 0x18,
    MultiplayerGameLobby = 0x19,
    MultiplayerPartyLobby = 0x1a,
    MultiplayerPartyOptions = 0x1b,
    MultiplayerSyslink = 0x1c,
    MultiplayerSyslinkFindServers = 0x1d,
    MultiplayerChangeGameOptions = 0x1e,
    MultiplayerPlayerSelect = 0x1f,
    MultiplayerXpTally = 0x20,
    MultiplayerResults = 0x21,
    MultiplayerScoreboard = 0x22,
    MultiplayerStats = 0x23,
    MultiplayerTutorials = 0x24,
    IngameFullscreenMap = 0x25,
    IngameMissionBriefing = 0x26,
    IngameActivityBriefing = 0x27,
    IngameMissionComplete = 0x28,
    IngameActivityComplete = 0x29,
    IngameUpgradesHud = 0x2a,
    IngameHandbookHud = 0x2b,
    IngameRailDriverHud = 0x2c,
    IngameDistrictLiberation = 0x2d,
    IngameWeaponCabinet = 0x2e,
    LoadCutscene = 0x2f,
    MainMenuIdle = 0x30,
    VideoCutscenePlay = 0x31,
    SaveLoadScreen = 0x32,
    Ps3Dlc = 0x33,
    ViewDlcScreen = 0x34,
    StatsScreen = 0x35,
    Credits = 0x36,
    VerifySavegame = 0x37,
    Shutdown = 0x38,
    DlcInit = 0x39,
    DlcShutdown = 0x3a,
    WcInit = 0x3b,
    WcShutdown = 0x3c,
    ResolutionChange = 0x3d,
    QuickPause = 0x3e,
    MultiplayerLiveFindServers = 0x3f,
}

addr_var!(addr(0x1118560), f32, frametime);
addr_var!(addr(0x111856C), f32, frames_per_second);
addr_var!(addr(0x1118574), f32, frametime_min);
addr_var!(addr(0x28071C2), bool, exit_startup_videos);
